// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'monitor_alloc_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MonitorAllocModel _$MonitorAllocModelFromJson(Map<String, dynamic> json) =>
    MonitorAllocModel(
      orderCnt: json['orderCnt'] as int?,
      allocCnt: json['allocCnt'] as int?,
      notAllocCnt: json['notAllocCnt'] as int?,
      cntTotal: json['cntTotal'] as int?,
      cntSTotal: json['cntSTotal'] as int?,
      cntMTotal: json['cntMTotal'] as int?,
      cntLTotal: json['cntLTotal'] as int?,
      cntEtcTotal: json['cntEtcTotal'] as int?,
      cnt1T: json['cnt1T'] as int?,
      cnt2T5: json['cnt2T5'] as int?,
      cnt3T5: json['cnt3T5'] as int?,
      cnt5T: json['cnt5T'] as int?,
      cnt5A: json['cnt5A'] as int?,
      cnt11T: json['cnt11T'] as int?,
      cnt15T: json['cnt15T'] as int?,
      cnt25T: json['cnt25T'] as int?,
      cnt20FT: json['cnt20FT'] as int?,
      cnt40FT: json['cnt40FT'] as int?,
      cntETC: json['cntETC'] as int?,
      amtTotal: json['amtTotal'] as int?,
      amtSTotal: json['amtSTotal'] as int?,
      amtMTotal: json['amtMTotal'] as int?,
      amtLTotal: json['amtLTotal'] as int?,
      amtEtcTotal: json['amtEtcTotal'] as int?,
      amt1T: json['amt1T'] as int?,
      amt2T5: json['amt2T5'] as int?,
      amt3T5: json['amt3T5'] as int?,
      amt5T: json['amt5T'] as int?,
      amt5A: json['amt5A'] as int?,
      amt11T: json['amt11T'] as int?,
      amt15T: json['amt15T'] as int?,
      amt25T: json['amt25T'] as int?,
      amt20FT: json['amt20FT'] as int?,
      amt40FT: json['amt40FT'] as int?,
      amtETC: json['amtETC'] as int?,
    );

Map<String, dynamic> _$MonitorAllocModelToJson(MonitorAllocModel instance) =>
    <String, dynamic>{
      'orderCnt': instance.orderCnt,
      'allocCnt': instance.allocCnt,
      'notAllocCnt': instance.notAllocCnt,
      'cntTotal': instance.cntTotal,
      'cntSTotal': instance.cntSTotal,
      'cntMTotal': instance.cntMTotal,
      'cntLTotal': instance.cntLTotal,
      'cntEtcTotal': instance.cntEtcTotal,
      'cnt1T': instance.cnt1T,
      'cnt2T5': instance.cnt2T5,
      'cnt3T5': instance.cnt3T5,
      'cnt5T': instance.cnt5T,
      'cnt5A': instance.cnt5A,
      'cnt11T': instance.cnt11T,
      'cnt15T': instance.cnt15T,
      'cnt25T': instance.cnt25T,
      'cnt20FT': instance.cnt20FT,
      'cnt40FT': instance.cnt40FT,
      'cntETC': instance.cntETC,
      'amtTotal': instance.amtTotal,
      'amtSTotal': instance.amtSTotal,
      'amtMTotal': instance.amtMTotal,
      'amtLTotal': instance.amtLTotal,
      'amtEtcTotal': instance.amtEtcTotal,
      'amt1T': instance.amt1T,
      'amt2T5': instance.amt2T5,
      'amt3T5': instance.amt3T5,
      'amt5T': instance.amt5T,
      'amt5A': instance.amt5A,
      'amt11T': instance.amt11T,
      'amt15T': instance.amt15T,
      'amt25T': instance.amt25T,
      'amt20FT': instance.amt20FT,
      'amt40FT': instance.amt40FT,
      'amtETC': instance.amtETC,
    };
